---
title: "Tile Plots - Variation Amongst Technical Replicates"
author: "Zack Gold (Helen just moved tile plots to separate file)"
date: "1/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(ggpmisc)
here()
library(see)
```

```{r Load in data}
MiFish_data <- readRDS(file = here("special_issue_manuscript","Data","mifish_tech_nReads.RDS"))
larvae_data <- readRDS(file = here("special_issue_manuscript","Data", "microscopy_tech_nReads.RDS"))
alphas <- read.csv(file = here("special_issue_manuscript","Data", "alpha_oceanic_all.csv"))

alphas %>% 
  mutate(., alpha = mean_log_alpha) %>% 
  mutate(., ID_mifish=Species) %>% distinct()-> alphas
```

```{r get total larval counts and total ASV reads}
counts_plus_reads <- left_join(MiFish_data, larvae_data)

# make vectors of total ASV reads and total larval counts
counts_plus_reads <- counts_plus_reads %>%
  mutate(bio_rep = paste(station_id, ext_rep, sep = "_")) %>%
  dplyr::select(-c(Sample, ID_sebastes, Unique_ID)) %>%
  distinct() 

counts_plus_reads %>% 
  unite(., Sample_ID, c("station_id","ext_rep","tech_rep"), sep=":") %>% 
  dplyr::select(-larval_counts) %>% 
  filter(., !is.na(mifish_reads)) %>% 
  group_by(Sample_ID) %>% 
  dplyr::summarise(tot_reads=sum(mifish_reads)) -> mifish_tot_reads

counts_plus_reads %>% 
  unite(., Sample_ID, c("station_id","ext_rep","tech_rep"), sep=":") %>% 
  dplyr::select(-mifish_reads) %>% 
  filter(., !is.na(larval_counts)) %>% 
  group_by(Sample_ID) %>% 
  dplyr::summarise(tot_counts=sum(larval_counts)) -> larvae_tot_counts
```

```{r More Data Wrangling}
counts_plus_reads %>% 
  unite(., Sample_ID, c("station_id","ext_rep","tech_rep"), sep=":",remove="F") %>% #create IDs
  left_join(mifish_tot_reads) %>% 
  left_join(larvae_tot_counts) %>% 
  mutate(., prop_reads= mifish_reads/tot_reads,
         prop_counts=larval_counts/tot_counts) %>% 
  filter(., ID_mifish %in% alphas$Species) %>% 
  left_join(alphas) %>% 
  mutate(larval_abundance = case_when(larval_counts > 250  ~"High Counts",
                              larval_counts >100  ~"Medium Counts",
                              larval_counts >10  ~"Low Counts",
                              larval_counts >0  ~"Super Low Counts",
                              TRUE ~"Not Counted"))-> calcofi_use


calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(mean_prop_reads = mean(prop_reads),
                   max_prop_reads=max(prop_reads),
                   min_prop_reads=min(prop_reads)) %>% 
  filter(., max_prop_reads >0) %>% 
  mutate(Drop_outs = case_when(min_prop_reads > 0 & max_prop_reads > 0 ~"Three reps above zero",
                              min_prop_reads == 0 & max_prop_reads > 0 ~"One rep is zero",#at least one rep?
                              min_prop_reads == 0 & max_prop_reads == 0 ~"All zero")) -> calcofi_dropout_prop


# get ID_mifish, station ID, ext rep, drop_out_count, drop_prop
calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  filter(larval_counts > 0) %>% 
  group_by(ID_mifish, station_id, ext_rep) %>% 
  dplyr::summarise(Drop_out_count = sum(prop_reads > 0)) %>% 
  mutate(., drop_prop = 1 - Drop_out_count / 3) -> calcofi_dropout_prop2


calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  filter(larval_counts > 0) %>% 
  group_by(ID_mifish, station_id, ext_rep) %>% 
  left_join(calcofi_dropout_prop) %>% 
  left_join(calcofi_dropout_prop2) %>% 
  filter(., !is.na(mean_prop_reads)) -> plotting_drop_outs
```

# Tile Plots: Mapping Proportion of Technical Replicates of Zero Reads
```{r Heat Map Surface (fluid)}
grandmin <- -0.01
grandmax <- 1.1

mybreaks <- seq(grandmin, ceiling(round(grandmax, 0)), length.out = 9)

plotting_drop_outs %>% 
  ggplot(aes(x=alpha, y=log(larval_counts), z=drop_prop)) +geom_contour_filled(breaks= mybreaks,size = 5, show.legend = TRUE)  + scale_colour_viridis_c()
  
  

ggsave(
file = here::here("figures", "drop_prop_alpha_counts_surface.png"),
width = 14,
height = 8
)

```

```{r 9-bin Heat Map}
plotting_drop_outs %>% 
  mutate(alpha_group = case_when(alpha > 0  ~ "High Alpha",
                                 alpha >-0.07  ~ "Medium Alpha",
                                 TRUE ~ "Low Alpha")) %>% 
  mutate(larval_abundance = case_when(larval_counts >100  ~ ">100 Larvae",
                                      larval_counts > 10  ~ ">10 Larvae",
                                 larval_counts > 0  ~ ">0 Larvae",
                                 TRUE ~ "No Larvae")) -> plotting_drop_outs_2

plotting_drop_outs_2$alpha_group <- factor(plotting_drop_outs_2$alpha_group, levels = c("Low Alpha","Medium Alpha","High Alpha"))

plotting_drop_outs_2$larval_abundance <- factor(plotting_drop_outs_2$larval_abundance, levels = c("No Larvae", ">0 Larvae", ">10 Larvae", ">100 Larvae"))

plotting_drop_outs_2 %>% 
  ungroup() %>% 
  group_by(alpha_group,larval_abundance) %>% 
  dplyr::summarise(`Proportion of Technical Replicates with Zero Reads`=mean(drop_prop)) %>% 
  ggplot(aes(x=alpha_group, y=larval_abundance, fill=`Proportion of Technical Replicates with Zero Reads`)) +geom_tile()  +scale_fill_viridis_c() + xlab("Amplification Efficiency") + ylab("Abundance")

ggsave(
file = here::here("figures", "tech_drop_tile.png"),
width = 14,
height = 8
)


```

```{r 6-bin Heat Map (removing replicates with 3 zero-reads)}
plotting_drop_outs %>% 
  mutate(alpha_group = case_when(alpha > 0  ~"High Alpha",
                              alpha >-0.07  ~"Medium Alpha",
                              TRUE ~"Low Alpha")) %>% 
    mutate(larval_abundance = case_when(# larval_counts >100  ~ ">100 Larvae",
      larval_counts >10  ~ ">10 Larvae",
                              larval_counts >0  ~ ">0 Larvae",
                              TRUE ~"No Larvae")) -> plotting_drop_outs_2

plotting_drop_outs_2$alpha_group <- factor(plotting_drop_outs_2$alpha_group, levels = c("Low Alpha","Medium Alpha","High Alpha"))

plotting_drop_outs_2$larval_abundance <- factor(plotting_drop_outs_2$larval_abundance, levels = c("No Larvae",
                                                                                                  ">0 Larvae",
                                                                                                  ">10 Larvae"))

plotting_drop_outs_2 %>% 
  ungroup() %>% 
  group_by(alpha_group,larval_abundance) %>% 
  dplyr::summarise(`Proportion of Technical Replicates with Zero Reads`=mean(drop_prop)) %>% 
  ggplot(aes(x=alpha_group, y=larval_abundance, fill=`Proportion of Technical Replicates with Zero Reads`)) +geom_tile()  +scale_fill_viridis_c() + xlab("Amplification Efficiency") + ylab("Abundance")

ggsave(
file = here::here("figures", "tech_drop_tile_6bins.png"),
width = 14,
height = 8
)


```


```{r 6-bin Heat Map (keeping replicates with 3 zero-reads)}
# all I did here was comment out one line of code

calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(mean_prop_reads = mean(prop_reads),
                   max_prop_reads=max(prop_reads),
                   min_prop_reads=min(prop_reads)) %>% 
#   filter(., max_prop_reads >0) %>% # here, leave in data that actually has all zeros 
  mutate(Drop_outs = case_when(min_prop_reads > 0 & max_prop_reads > 0 ~"Three reps above zero",
                               min_prop_reads == 0 & max_prop_reads > 0 ~"One rep is zero",
                               min_prop_reads == 0 & max_prop_reads == 0 ~"All zero")) -> calcofi_dropout_prop


calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  filter(larval_counts >0) %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(Drop_out_count = sum(prop_reads>0)) %>% 
  mutate(., drop_prop = 1- Drop_out_count/3)-> calcofi_dropout_prop2


calcofi_use %>% 
  filter(., !is.na(mifish_reads)) %>%  
  filter(larval_counts >0) %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  left_join(calcofi_dropout_prop) %>% 
  left_join(calcofi_dropout_prop2) %>% 
  filter(., !is.na(mean_prop_reads))-> plotting_drop_outs



plotting_drop_outs %>% 
  mutate(alpha_group = case_when(alpha > 0  ~"High Alpha",
                                 alpha >-0.07  ~"Medium Alpha",
                                 TRUE ~"Low Alpha")) %>% 
  mutate(larval_abundance = case_when(# larval_counts >100  ~ ">100 Larvae",
    larval_counts >10  ~ ">10 Larvae",
    larval_counts >0  ~ ">0 Larvae",
    TRUE ~"No Larvae")) -> plotting_drop_outs_2

plotting_drop_outs_2$alpha_group <- factor(plotting_drop_outs_2$alpha_group, levels = c("Low Alpha","Medium Alpha","High Alpha"))

plotting_drop_outs_2$larval_abundance <- factor(plotting_drop_outs_2$larval_abundance, levels = c("No Larvae",
                                                                                                  ">0 Larvae",
                                                                                                  ">10 Larvae"))

plotting_drop_outs_2 %>% 
  ungroup() %>% 
  group_by(alpha_group,larval_abundance) %>% 
  dplyr::summarise(`Proportion of Technical Replicates with Zero Reads`=mean(drop_prop)) %>% 
  ggplot(aes(x=alpha_group, y=larval_abundance, fill=`Proportion of Technical Replicates with Zero Reads`)) +geom_tile()  +scale_fill_viridis_c() + xlab("Amplification Efficiency") + ylab("Abundance")

ggsave(
file = here::here("figures", "tech_drop_tile_6bins_123nondetections.png"),
width = 14,
height = 8
)

```

```{r Helen's function + plot }
# now takes long form data, also includes tech reps with 3 zeros 
# - using Zack's proportion metric - just using cut() to make breaks

drop_function_df <- calcofi_use %>%
  filter(., !is.na(mifish_reads)) %>% 
  filter(larval_counts > 0) 

# When you change countBreaks and ampBreaks, must change levels of outputdf (lines 287-293)


TechDrops.vs.CountsAmps <- function(input_df, countBreaks, ampBreaks){
  
  total_binned_df <- data.frame(input_df, abundance_bin=cut(input_df$larval_counts, na.rm =T, breaks = countBreaks), 
                                ampef_bin = cut(input_df$alpha, na.rm= T, breaks = ampBreaks))  # sort abundance and amp efficiency into quantiles with all input data
  
  unique_bins <- unique(total_binned_df[,c("abundance_bin","ampef_bin" )]) # all unique amp bin and abundance bin combinations
  unique_bins <- unique_bins[complete.cases(unique_bins), ]
  
  list <- replicate(length(unique_bins[,1]), rep(NA, length=nrow(total_binned_df)), simplify = FALSE) # list of empty vectors (length of input dataframe), one vector for all the row indices corresponding to an unique amp&abundance bin combination
  
  propdrops <- unique_bins %>% mutate(dropout_proportion = rep(NA, length(unique_bins[,1]))) %>% mutate(totalprop_in_bin = rep(NA, length(unique_bins[,1])))
  
  # Gets index values in input dataframe corresponding to a the numeric factor levels for given abundance/amp bin 
  bin_levels_list <- lapply(total_binned_df[,c('abundance_bin','ampef_bin')], as.numeric)
  
  for(i in 1:length(unique_bins[,1])){
    bin <- as.numeric(unique_bins[i,]) # get vector of numeric factor levels of that abundance/amp bin (so c([1,3], [0.1,0.3]) would be c(1,1))
    
      bin_indices <- which(bin_levels_list$abundance_bin == bin[1] & bin_levels_list$ampef_bin == bin[2])
  
    specific_bin_df <- total_binned_df[bin_indices,] # subset data to only include given abundance/amp bin, get prop of dropouts
    
    dropouts <-  specific_bin_df %>% 
      group_by(ID_mifish,station_id,ext_rep) %>% 
      dplyr::summarise(Drop_out_count = sum(prop_reads>0)) %>% 
      mutate(., drop_prop = 1- Drop_out_count/3)
    
    propdrops[i,3] <- mean(dropouts$drop_prop)
    
    propdrops$totalprop_in_bin[i] <- length(bin_indices)/nrow(total_binned_df) # proportion taken up by that bin 
  }
  
  print(propdrops %>% 
    ungroup() %>% 
    group_by(ampef_bin,abundance_bin) %>% 
    dplyr::summarise(`Proportion of Technical Replicates with Zero Reads`=dropout_proportion) %>%
    ggplot() + 
    geom_tile(aes(x=ampef_bin, y=abundance_bin, fill=`Proportion of Technical Replicates with Zero Reads`))  +
    scale_fill_viridis_c() + xlab("Amplification Efficiency") + ylab("Abundance"))
  
  return(propdrops)
}

TechDrops.vs.CountsAmps(drop_function_df, countBreaks = 2, ampBreaks = 2)

# final output df gives the count/amp bin combinations, the Proportion of Technical Replicates with Zero Reads in each, and the how much of the whole dataset each bin makes up

```



