---
title: "joe.rare.sp.BC"
author: "Helen Casendino, Joe Duprey"
date: "7/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vegan)
library(reshape)
# source("dissimilarity.exploration.Rmd")
```


```{r load data}
full.proportion.reads <- read.csv('../data/PCR.proportions.clean.csv')
```

```{r}
full.proportion.long <- full.proportion.reads %>%
  pivot_longer(cols=c('X1','X2','X3'), names_to='tech',values_to='PropRead')
```

```{r}
#bioVector = list of unique biological replicate IDs, indexCols = col numbers of eDNA proportion values (by PCR #). df needs to have 3 columns corresponding to eDNA proportions of different PCR runs

bray_by_sample <- function(df, bioVector, indexCols){  
  
    #bray.mat <- matrix(NA, nrow = length(bioVector), ncol = 3, dimnames = list(bioVector, c(1.2,2.3,1.3)))
    bray.mat <- matrix(NA, nrow = length(bioVector), ncol = 3, dimnames = list(bioVector, c('onetwo','twothree','onethree')))
    # different PCR rep combinations
  
  for(i in 1:length(bioVector)){
    sample.tib <- df[df$bio == bioVector[i],indexCols]
    bray.tib <- t(sample.tib)
    bray.results <- as.matrix(vegdist(bray.tib, method="bray", na.rm = T))
    
    #print(i)
    #print(bray.results)
    bray.mat[i,1] <- bray.results[1,2]
    bray.mat[i,2] <- bray.results[2,3]
    bray.mat[i,3] <- bray.results[1,3]
  }
    
    return(bray.mat)
}

bray.mat.test <- bray_by_sample(full.proportion.reads, unique(full.proportion.reads$bio), c(4:6))

```

```{r}

filter_proprank <- function(df, proportion, use_rank=TRUE) {
  
  if (use_rank==FALSE) {
    result.long <- df %>%
    filter(df$PropRead >= proportion) 
  } 
  
  else {
  # the original observations in long data form
  original.obs <- df
  original.obs$ID <- seq.int(nrow(original.obs))

  # arange observation by ascending ReadProp, then "skim" off rows based on given prop
  rows_to_zero <- original.obs %>%
    filter(PropRead > 0) %>%
    arrange(PropRead) %>%
    filter(row_number() <= proportion * n()) # * n()  # should this be great or less than *******

  # if observations are in the skimmed rows, set them to zero
  result.long <- original.obs %>%
    mutate(PropRead = ifelse(ID %in% rows_to_zero$ID, 0, PropRead))
  
  }
  # flatten the df to feed into bray_by_sample() function 
  result.wide <- result.long %>%
    select(Miseq_run, bio, tech, Hash, PropRead) %>%
    pivot_wider(names_from=tech, values_from=PropRead, values_fill=0) 
  
  BC.by.bio <- as.data.frame(bray_by_sample(result.wide, unique(result.wide$bio), c(4:6)))
  ####
  BC.by.bio$prop <- proportion # show which prop cutoff it came from on the big df 
  # get the mean distance per bio rep
  BC.by.bio$mean.bio <- (BC.by.bio$onetwo + BC.by.bio$twothree + BC.by.bio$onethree) /3 
  # get the mean distance for all bio reps combined
  BC.by.bio$mean.all <-mean(BC.by.bio$mean.bio)
    
  return(BC.by.bio)
  
}

test <- filter_proprank(full.proportion.long, 0, use_rank=FALSE)
```

```{r}

x <- seq(0,0.2, by=0.005)
datalist = vector(mode = "list", length = length(x))
it <- 1 

for (i in x){
  
  dat <- filter_proprank(full.proportion.long, i, use_rank=FALSE) 
  #hist(dat$mean.bio, breaks=30)
  print(i)
  datalist[[it]] <- dat
  
  it <- it+1
}

eily.plot.df = do.call(rbind, datalist)
```

```{r}
ggplot(eily.plot.df, aes(x=prop, y=mean.all)) + geom_point()
```

