---
title: "BC_eelgrass"
author: "Joe Duprey, Helen Casendino, Kai Vennemann"
date: "10/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(vegan)
library(stringi)
source("../functions/COMM_functions.R")
```

```{r import eelgrass data}
# load ASV table with raw reads, need to confirm this is prior to QC
eelgrass_rawreads <-read_csv("../../input/eelgrass_halo/ASV_table_r5.csv")
```
```{r}
# first some data standardization YAY!!! 
eel_long_props <- eelgrass_rawreads %>%
  separate(col = sample, into = c("str1","str2","day","month","tech","seq_run"), sep = "_") %>% #divide up the sample names, regex method of doing this? 
  unite(col = "bio", "str1":"month", sep = "_") %>%
  mutate(seq_run = gsub("r", "", seq_run)) %>%
  mutate(tech = case_when( # tech reps need to be ints for find_PCR_BCDs()
    tech == "A" ~ 1,
    tech == "B" ~ 2,
    tech == "C" ~ 3
   ))

eel_long_props$seq_run <- as.numeric(eel_long_props$seq_run)

# sanity check for tech values - should all be 1,2,3
print(unique(eel_long_props$tech))

# calculate read proportions because thats what we work with here ~ ~ 
eel_long_props <- eel_long_props %>%
  group_by(bio, tech) %>%
  mutate(prop = nReads / sum(nReads))

# rename cols so they work with find_PCR_BCDs()
eel_long_props <- rename(eel_long_props, reads = nReads)
eel_long_props <- rename(eel_long_props, hash = Hash)
eel_long_props <- ungroup(eel_long_props) # ungroup!!

```

```{r}
# call the function!  
eel_PCR_output <- find_PCR_BCDs(eel_long_props)
```
```{r}
find_bottle_BCDs(eel_long_props)
```

